# https://docs.render.com/blueprints
services:
  - type: web
    name: joblens-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: QDRANT_COLLECTION
        value: Joblens
      - key: LANGSMITH_TRACING
        value: "true"
      - key: LANGSMITH_ENDPOINT
        value: https://api.smith.langchain.com
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        value: joblens
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /health
